# Copyright 2026 The OpenChoreo Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: tracing-adapter
  namespace: {{ .Release.Namespace }}
  labels:
    app: tracing-adapter-openobserve
spec:
  type: ClusterIP
  ports:
  - port: 9099
    targetPort: 9099
    protocol: TCP
    name: http
  selector:
    app: tracing-adapter-openobserve
